# NumPy Array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
a= [1,2,3]
print(a)

[1, 2, 3]


In [5]:
print(type(a))

<class 'list'>


In [6]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [7]:
y = np.ones(5)
print(y)

[1. 1. 1. 1. 1.]


In [8]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
y = np.array([1,2,3,4,5,6])
print(y)

[1 2 3 4 5 6]


In [10]:
y[0]

1

In [11]:
y[2]

3

In [12]:
y[0:3]

array([1, 2, 3])

In [13]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [17]:
b = np.arange(5, 15, 3)
print(b)

[ 5  8 11 14]


In [22]:
a = np.linspace(0, 10, 5)
print(a)

[ 0.   2.5  5.   7.5 10. ]


In [23]:
x = np.ones(5, dtype= np.int64)
print(x)

[1 1 1 1 1]


In [24]:
a = np.array([100,1,39, 69,2])
print(a)

[100   1  39  69   2]


In [25]:
print(np.sort(a))

[  1   2  39  69 100]


In [35]:
a= np.array([1,2,3])
b= np.array([10,11,12])

In [36]:
print(a)

[1 2 3]


In [37]:
print(b)

[10 11 12]


In [38]:
np.concatenate((a,b), axis=0)

array([ 1,  2,  3, 10, 11, 12])

In [40]:
x = np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [41]:
x[0]= 100

In [42]:
print(x)

[100   2   3   4]
