# Array Functions

In [1]:
import numpy as np

In [2]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [3]:
a.ndim

1

In [4]:
a.shape

(5,)

In [5]:
a.size

5

In [6]:
b = np.zeros((2,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
b.ndim

2

In [8]:
b.shape

(2, 4)

In [9]:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [10]:
y = np.ones((2,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
a= np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
b = np.eye(3,3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
c = np.eye(3,4)
print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [15]:
x = np.diag([4,5,6,7,8,9])
print(x)

[[4 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 0 6 0 0 0]
 [0 0 0 7 0 0]
 [0 0 0 0 8 0]
 [0 0 0 0 0 9]]


In [16]:
np.diag(x)

array([4, 5, 6, 7, 8, 9])

In [17]:
a = np.random.randint(1,20,10)
print(a)

[19  1 15  8  4  7  3 13 13 18]


In [18]:
x = np.random.rand(5)
print(x)

[0.03865804 0.83250979 0.42397034 0.14599605 0.21231472]


In [19]:
y = np.random.rand(4,4)
print(y)

[[0.49881931 0.32931193 0.95121498 0.41329612]
 [0.21444861 0.54024262 0.23929674 0.99012386]
 [0.73604056 0.44009208 0.70327623 0.20526524]
 [0.26423392 0.86620519 0.37784153 0.02044386]]


In [21]:
a = np.random.randn(5)
print(a)

[ 1.87509185 -0.21225145 -0.28871856  1.01980189  0.05224198]


In [3]:
def add(a,b=5,c):
    return a+b+c

SyntaxError: non-default argument follows default argument (<ipython-input-3-6fee594f1f51>, line 1)