# Numpy array

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b = [1,2,3,4,5]
print(b)

[1, 2, 3, 4, 5]


In [6]:
print(type(b))

<class 'list'>


In [7]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [8]:
y = np.ones(5)
print(y)

[1. 1. 1. 1. 1.]


In [9]:
a = np.empty(2)
print(a)

[ 3.46704325e+158 -1.20193136e-027]


In [10]:
b = np.arange(5)
print(b)

[0 1 2 3 4]


In [11]:
print(type(b))

<class 'numpy.ndarray'>


In [12]:
x = np.linspace(0,10, 5)
print(x)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
a = np.ones(5, dtype = np.int64)
print(a)

[1 1 1 1 1]


In [14]:
a = np.ones(5, dtype = np.int32)
print(a)

[1 1 1 1 1]


In [15]:
a = np.ones(5, dtype = np.float32)
print(a)

[1. 1. 1. 1. 1.]


In [16]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [17]:
a[0]

1

In [18]:
a[4]

5

In [19]:
a[10]

IndexError: index 10 is out of bounds for axis 0 with size 5

In [20]:
a[0:3]

array([1, 2, 3])

In [21]:
a[-1]

5

In [23]:
x = np.array([10,1,5,2])
print(x)

[10  1  5  2]


In [24]:
np.sort(x)

array([ 1,  2,  5, 10])

In [25]:
a = np.array([1,2,3])
b = np.array([5,6,7])
np.concatenate((a,b), axis=0)

array([1, 2, 3, 5, 6, 7])

In [26]:
x = np.array([2,5,7,1,0])
print(x)

[2 5 7 1 0]


In [27]:
x[0]= 100

In [28]:
print(x)

[100   5   7   1   0]
