# Conditional Selection

In [1]:
import numpy as np

In [2]:
a = np.arange(1,21)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [3]:
a > 10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [4]:
b = a > 10

In [5]:
print(b)

[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True]


In [6]:
a[a > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
a[a < 10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
a[a%2 !=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
a[a==5]

array([5])

In [18]:
a[a < 5]

array([1, 2, 3, 4])

In [19]:
a[a%2 !=0] = 0

In [20]:
print(a)

[ 0  2  0  4  0  6  0  8  0 10  0 12  0 14  0 16  0 18  0 20]
