# Functions in NumPy

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,10,9).reshape(3,3)
print(a)

[[5 4 3]
 [6 5 7]
 [6 3 8]]


In [3]:
a.ndim

2

In [4]:
a.shape

(3, 3)

In [5]:
np.sum(a)

47

In [6]:
np.min(a)

3

In [7]:
np.max(a)

8

In [8]:
np.min(a, axis=1)

array([3, 5, 3])

In [9]:
np.max(a, axis=1)

array([5, 7, 8])

In [10]:
np.min(a, axis=0)

array([5, 3, 3])

In [11]:
np.max(a, axis=0)

array([6, 5, 8])

In [13]:
print(a)

[[5 4 3]
 [6 5 7]
 [6 3 8]]


In [12]:
np.cumsum(a)

array([ 5,  9, 12, 18, 23, 30, 36, 39, 47], dtype=int32)

In [14]:
np.cumsum(a, axis=0)

array([[ 5,  4,  3],
       [11,  9, 10],
       [17, 12, 18]], dtype=int32)