# Indexing and Slicing - 1 D Array

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [4]:
a.ndim

1

In [5]:
a.size

5

In [6]:
a.shape

(5,)

In [7]:
a[:]

array([1, 2, 3, 4, 5])

In [8]:
a[::]

array([1, 2, 3, 4, 5])

In [9]:
a[2:4]

array([3, 4])

In [10]:
a[1:4]

array([2, 3, 4])

In [11]:
a[1:]

array([2, 3, 4, 5])

In [13]:
a[:4]

array([1, 2, 3, 4])

In [19]:
a[::-1]

array([5, 4, 3, 2, 1])

In [20]:
a[-2:]

array([4, 5])

In [21]:
a[-1:]

array([5])

In [27]:
a[-2:-1]

array([4])

In [28]:
a[:-2]

array([1, 2, 3])