# Indexing and Slicing - 2 D Array

In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
x.ndim

2

In [5]:
x.shape

(3, 3)

In [6]:
x.size

9

In [7]:
type(x)

numpy.ndarray

In [8]:
x[0][0]

1

In [10]:
x[0]

array([1, 2, 3])

In [11]:
x[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
x[0]

array([1, 2, 3])

In [16]:
x[1]

array([4, 5, 6])

In [17]:
x[2]

array([7, 8, 9])

In [18]:
x[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [20]:
x[:2, 1:3]

array([[2, 3],
       [5, 6]])

In [21]:
x[:3, 0:4]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
x[:1, 1:3]

array([[2, 3]])

In [23]:
x[2:, 2:]

array([[9]])