# Mathematical Operation

In [2]:
import numpy as np

In [3]:
a = np.array([5,10,15,20,25,30])
print(a)

[ 5 10 15 20 25 30]


In [4]:
a.ndim

1

In [5]:
a.shape

(6,)

In [6]:
a.size

6

In [7]:
type(a)

numpy.ndarray

In [8]:
np.min(a)

5

In [9]:
np.max(a)

30

In [10]:
np.argmin(a)

0

In [11]:
np.argmax(a)

5

In [12]:
np.sqrt(a)

array([2.23606798, 3.16227766, 3.87298335, 4.47213595, 5.        ,
       5.47722558])

In [13]:
np.sin(a)

array([-0.95892427, -0.54402111,  0.65028784,  0.91294525, -0.13235175,
       -0.98803162])

In [14]:
np.cos(a)

array([ 0.28366219, -0.83907153, -0.75968791,  0.40808206,  0.99120281,
        0.15425145])

In [15]:
# linspace
b = np.linspace(1,2,10)
print(b)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]
