# One Dimensional Array

In [1]:
import numpy as np

In [2]:
a= [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [3]:
a_array = np.array(a)
print(a_array)

[1 2 3 4 5]


In [4]:
type(a_array)

numpy.ndarray

In [5]:
type(a)

list

In [6]:
a_array.ndim

1

In [7]:
a_array.shape

(5,)

In [8]:
b = np.array([5,6,7,8,9])
print(b)

[5 6 7 8 9]


In [9]:
type(b)

numpy.ndarray

In [10]:
b.ndim

1

In [11]:
b.shape

(5,)

In [13]:
n = int(input("Please enter size of the array: "))
result = []
for i in range(n):
    result.append(i)
    
result = np.array(result)
print(result)
print(type(result))
result.ndim

Please enter size of the array: 5
[0 1 2 3 4]
<class 'numpy.ndarray'>


1