# Reshape Array

In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,20,20)
print(a)

[ 9  8  4 10  6 13  2  9 15  9  7 15  6  5 18 15  9 10 15  9]


In [3]:
a.shape

(20,)

In [4]:
a.ndim

1

In [5]:
a.size

20

In [6]:
b = a.reshape(5,4)
print(b)

[[ 9  8  4 10]
 [ 6 13  2  9]
 [15  9  7 15]
 [ 6  5 18 15]
 [ 9 10 15  9]]


In [7]:
b.shape

(5, 4)

In [8]:
b.ndim

2

In [9]:
b.size

20

In [10]:
c = a.reshape(5,2,2)
print(c)

[[[ 9  8]
  [ 4 10]]

 [[ 6 13]
  [ 2  9]]

 [[15  9]
  [ 7 15]]

 [[ 6  5]
  [18 15]]

 [[ 9 10]
  [15  9]]]


In [11]:
c.shape

(5, 2, 2)

In [12]:
c.ndim

3

In [13]:
c.size

20

In [14]:
# Convert two dimension array into one dimension
x = np.array([[1,2,3], [4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [15]:
x.shape

(2, 3)

In [16]:
x.ndim

2

In [18]:
y = x.reshape(6)
print(y)

[1 2 3 4 5 6]


In [19]:
y.shape

(6,)

In [20]:
y.ndim

1

In [21]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [22]:
a.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
a.reshape(-1,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
a.reshape(4,-1)

ValueError: cannot reshape array of size 6 into shape (4,newaxis)