# Stacking

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [4]:
b = np.array([6,7,8,9,10])
print(b)

[ 6  7  8  9 10]


In [5]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
import pandas as pd

In [16]:
data = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/arrhythmia/arrhythmia.data",
                  sep=",")

In [17]:
data.head()

75  0  190  80   91  193  371  174  121  -16  ... 0.0.38   9.0 -0.9 0.0.39  \
0  56  1  165  64   81  174  401  149   39   25  ...    0.0   8.5  0.0    0.0   
1  54  0  172  95  138  163  386  185  102   96  ...    0.0   9.5 -2.4    0.0   
2  55  0  175  94  100  202  380  179  143   28  ...    0.0  12.2 -2.2    0.0   
3  75  0  190  80   88  181  360  177  103  -16  ...    0.0  13.1 -3.6    0.0   
4  13  0  169  51  100  167  321  174   91  107  ...   -0.6  12.2 -2.8    0.0   

  0.0.40  0.9.3  2.9.1  23.3  49.4   8  
0    0.0    0.2    2.1  20.4  38.8   6  
1    0.0    0.3    3.4  12.3  49.0  10  
2    0.0    0.4    2.6  34.6  61.6   1  
3    0.0   -0.1    3.9  25.4  62.8   7  
4    0.0    0.9    2.2  13.5  31.1  14  

[5 rows x 280 columns]

In [11]:
data.tail()

75  0  190  80   91  193  371  174  121  -16  ... 0.0.38   9.0  -0.9  \
446  53  1  160  70   80  199  382  154  117  -37  ...    0.0   4.3  -5.0   
447  37  0  190  85  100  137  361  201   73   86  ...    0.0  15.6  -1.6   
448  36  0  166  68  108  176  365  194  116  -85  ...    0.0  16.3 -28.6   
449  32  1  155  55   93  106  386  218   63   54  ...   -0.4  12.0  -0.7   
450  78  1  160  70   79  127  364  138   78   28  ...    0.0  10.4  -1.8   

    0.0.39 0.0.40  0.9.3  2.9.1  23.3  49.4   8  
446    0.0    0.0    0.7    0.6  -4.4  -0.5   1  
447    0.0    0.0    0.4    2.4  38.0  62.4  10  
448    0.0    0.0    1.5    1.0 -44.2 -33.2   2  
449    0.0    0.0    0.5    2.4  25.0  46.6   1  
450    0.0    0.0    0.5    1.6  21.3  32.8   1  

[5 rows x 280 columns]

In [12]:
names = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/arrhythmia/arrhythmia.names")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 5, saw 3
