# Numpy Stacking

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [3]:
# Horizontal stacking
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
print(a)

[1 2 3 4 5]


In [5]:
print(b)

[ 6  7  8  9 10]


In [6]:
# Vertical stacking
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [8]:
x = np.random.randint(1,10,9).reshape(3,3)
y = np.random.randint(11,20,9).reshape(3,3)

In [9]:
print(x)

[[7 5 9]
 [6 2 8]
 [6 7 5]]


In [10]:
print(y)

[[17 19 12]
 [17 17 18]
 [11 13 18]]


In [11]:
np.hstack((x,y))

array([[ 7,  5,  9, 17, 19, 12],
       [ 6,  2,  8, 17, 17, 18],
       [ 6,  7,  5, 11, 13, 18]])

In [12]:
np.vstack((x,y))

array([[ 7,  5,  9],
       [ 6,  2,  8],
       [ 6,  7,  5],
       [17, 19, 12],
       [17, 17, 18],
       [11, 13, 18]])