# Two Dimensional Array

In [2]:
import numpy as np

In [3]:
a = [[1,2,3], [4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [4]:
type(a)

list

In [5]:
a_array = np.array(a)
print(a_array)

[[1 2 3]
 [4 5 6]]


In [6]:
type(a_array)

numpy.ndarray

In [7]:
a_array.ndim

2

In [8]:
a_array.size

6

In [9]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
type(b)

numpy.ndarray

In [11]:
b.size

6

In [12]:
b.shape

(2, 3)