# View/Copy

In [1]:
# View

import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6])
print(x)

[1 2 3 4 5 6]


In [4]:
x_new = x[2:5]

In [5]:
print(x_new)

[3 4 5]


In [7]:
x_new[:] = 0

In [8]:
print(x_new)

[0 0 0]


In [9]:
print(x)

[1 2 0 0 0 6]


In [10]:
# copy
y = np.array([5,6,7,8,9])
print(y)

[5 6 7 8 9]


In [11]:
x_new = x[2:5].copy()

In [12]:
x_new[:] = 0

In [13]:
print(x_new)

[0 0 0]


In [14]:
print(y)

[5 6 7 8 9]
