# Where function

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
a.ndim

1

In [4]:
a.shape

(5,)

In [5]:
np.where(a==2)

(array([1], dtype=int64),)

In [6]:
np.where(a==3)

(array([2], dtype=int64),)

In [7]:
b = np.array([1,2,3,4,5,6])
print(b)

[1 2 3 4 5 6]


In [8]:
np.where(b < 4)

(array([0, 1, 2], dtype=int64),)

In [9]:
np.where(b > 5)

(array([5], dtype=int64),)

In [10]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(x)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
# Even numbers
np.where(x%2==0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [12]:
# Odd numbers
np.where(x%2!=0)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [14]:
# searchsorted
x = np.array([1,2,3,4,10,11,15])
print(x)

[ 1  2  3  4 10 11 15]


In [15]:
np.searchsorted(x, 8)

4

In [16]:
np.searchsorted(x,12)

6